# Generated by Django 3.2.10 on 2021-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countrymap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('riskmetrics', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'list',
            },
        ),
    ]
