# Generated by Django 3.2.10 on 2021-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_map_master', '0004_alter_countrymap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymap',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
