# Generated by Django 4.0 on 2021-12-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_map_master', '0006_alter_countrymap_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
